version: '1'
services:
  crudApp:
    image: vaddinaveen94/mytomcat:crudapp
    container_name: crudapp
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_DB_HOST: mysql:3306
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: supersecret
      MYSQL_DB_NAME: crudApp
    volumes:
      - crudapp-volume:/var/lib/crudapp
    depends_on:
      - mysql
  mysql:
    image: vaddinaveen94/my-mysql:mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  crudapp-volume:
  mysql-volume:
